### ISSUE TITLE
Missing data needs to be checked

### ISSUE THREAD

**Issue by SimonHettrick** [softwaresaved/RSE-Survey-2016#3]
In the gender question, we provide answers for the number of people who responded male and female, but we don't provide details of those who responded N/A, other, Don't want to say, etc.

if we don't include these results, we risk implying different results to those we actually measured (i.e. if we say 88.3% of respondents are male, then that implies that 88.3% of the entire survey respondents are male. But they're not, only 88.3% of the people who responded to that question are male).

We need to make sure we haven't overlooked this type of data from all the other questions too.

**Comment by Oliph** [comment]
fixed
